name: Nightly Deploy

on:
  schedule:
    - cron: "* 0 * * *"
  workflow_dispatch:
    branches: 'master'

jobs:
  
  build:

    name: Build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci

      - name: "Build"
        run: |
          git config --global user.name 'CI/CD'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          hub clone -b releases ${{ github.repository }} dist
          cd dist
          git pull
          npm run build:win
          git add *.exe
          git commit -m "Build: $(cat ../package.json | jq -r .version) (Nightly)"
          git push